config/routes.rb
Rails.application.routes.draw do
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout'  => :destroy
  end

  # // for time being lets open letter opener for all envs
  mount LetterOpenerWeb::Engine, at: "/letter_opener" #if Rails.env.development?

  root 'home#index', as: 'home'
  get "homepage_poll", to: 'home#poll'
  get "verify/:token", action: :verify, controller: :users, as: 'verify'

  resources :users, only: [:new, :create] do
    get "my_profile", on: :collection
  end

  resources :password_resets, only: [:new, :create, :edit, :update], param: :token

  resources :addresses, only: [:create, :new]
  resources :orders, only: :index do
    collection do
      get "buy_now"
      get "payment"
      post "charge"
      get "checkout"
    end
    member do
      get "add_to_cart"
      delete "rem_from_cart"
      get "select_address"
    end
  end

  namespace :admin do
    get "/", to: "deals#index"
    get 'top_customers', to: "users#top_customers"
    resources :deals do
      member do
        get "check_publishability"
        get "delete_image_attachment"
        get "publish"
        get "unpublish"
      end
    end
    resources :orders, only: [:index, :show] do
      member do
        get "cancel"
        get "shipped"
        get "delivered"
      end
    end
  end

  namespace :api do
    get 'deals/live', to: 'deals#live' 
    get 'deals/past', to: 'deals#past' 
    get 'myorders/:token', to: 'orders#index'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id               :bigint           not null, primary key
#  total_amount     :decimal(, )
#  total_tax        :decimal(, )
#  address_id       :bigint
#  user_id          :bigint           not null
#  deleted_at       :datetime
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  state            :integer          default("cart"), not null
#  line_items_count :integer
#  placed_at        :datetime
#
class Order < ApplicationRecord
  enum state: {
    cart: 0,
    paid: 1,
    placed: 2,
    shipped: 3,
    delivered: 4,
    cancelled: 5,
    refunded: 6
  }

  acts_as_paranoid
  define_model_callbacks :place_order, :mark_shipped, :mark_delivered, :mark_cancelled, only: :after

  validate :ensure_user_address, :ensure_payment_made, if: -> { placed? || shipped? || delivered? }
  validates :line_items_count, numericality: { greater_than: 0 }, if: -> { placed? }
  validate :ensure_state_transition, if: -> { state_change }

  has_many :line_items, dependent: :destroy
  has_many :deals, through: :line_items
  has_many :payments, dependent: :destroy
  has_many :order_histories, dependent: :destroy
  belongs_to :user
  belongs_to :address, optional: true

  after_place_order :send_placed_mailer
  after_mark_shipped :state_shipped
  after_mark_delivered :state_delivered
  after_mark_cancelled :state_cancelled

  scope :placed_orders, ->{ where(state: :placed).or where(state: :shipped).or where(state: :delivered) }
  scope :paid_orders, -> { where.not(state: :cart) }
  scope :shipped, -> { where(state: :shipped) }
  scope :delivered, -> { where(state: :delivered) }

  def number
   "#{(placed_at || created_at).to_s(:number)}-#{id}"
  end

  def add_item(deal_id)
    deal = Deal.live_deals(Time.current).find_by(id: deal_id)
    deal.present? && deal.saleable_qty_available? && can_user_buy?(deal.id) && (item = line_items.create(deal: deal, quantity: LINEITEMS[:default_quantity])) && item.persisted?
  end

  def remove_item(line_item_id)
    line_items.find_by(id: line_item_id)&.destroy
  end

  def place_order
    run_callbacks :place_order do
      unless paid?
        return false
      end

      line_items.includes(:deal).each do |line_item|
        unless line_item.deal.live? || can_user_buy?(line_item.deal_id) || line_item.deal.check_inventory(line_item.quantity)
          return false
        end
      end

      transaction do
        if update_inventory
          self.state = self.class.states[:placed]
          self.placed_at = Time.current
          #FIXME_AB: use create! here so that it raise an eception if failed and transaction rollbacks, same at other places
          save! && order_histories.create!(state: state, note: "Order Placed")
        else
          raise StandardError.new "Update Inventory Failure"
          return false
        end
      end
    rescue StandardError
      logger.tagged("Order: payments[refund]") do
        if process_refunds
          logger.info { "Order state changed to: #{state}, sending refund_intimation mailer" }
          OrderMailer.refund_intimation(id).deliver_later
        end
      end
    false
    end
  end


  def process_refunds
    transaction do
      if payments.success.map(&:refund).all?{ |refund_status| refund_status}
        logger.info { "Refund process success, updating order state to refund state" }
        order_histories.create!(state: state, note: "Refund success")
        update(state: self.class.states[:refunded])
      else
        logger.info { "some payments could not be refunded" }
      end
    end
  end

  def set_address!(address)
    self.address = address
    save
  end

  def update_totals
    self.total_amount = line_items.sum(&:sub_total)
    self.total_tax = line_items.sum(&:sub_tax_total)
  end

  def make_payment(token)
    logger.info { "initiating make_payment method against order id: #{id}, calling stripe_transact after checks & building payment" }
    paid = self.class.states[:paid]
    cart? && address && payments.build.stripe_transact(token) && update(state: paid) && order_histories.create!(state: paid, note: "Payment success")
  end

  def mark_as_shipped!(note)
    transaction do
      run_callbacks :mark_shipped do
        self.state = Order.states[:shipped]
        save && (event = order_histories.create!(state: state, note: note)) && event.persisted?
      end
    end
  end

  def mark_as_delivered!(note)
    transaction do
      run_callbacks :mark_delivered do
        self.state = Order.states[:delivered]
        save && (event = order_histories.create!(state: state, note: note)) && event.persisted?
      end
    end
  end

  def mark_as_cancelled!(note)
    transaction do 
      run_callbacks :mark_cancelled do
        self.state = Order.states[:cancelled]
        save && process_refunds && (event = order_histories.create!(state: state, note: note)) && event.persisted?
      end
    end
  end

  private def state_shipped
    if shipped?
      OrderMailer.shipped(id).deliver_later
    end
  end

  private def state_delivered
    if delivered?
      OrderMailer.delivered(id).deliver_later
    end
  end

  private def state_cancelled
    if refunded?
      OrderMailer.refund_intimation(id).deliver_later
    end
  end

  private def ensure_state_transition
    if !(STATE_TRASITIONS[state_was].include?(state))
      errors.add(:state, "transition from #{state_was} to #{state} is not allowed")
    end
  end

  private def update_inventory
    line_items.each do |line_item|
      unless line_item.deal.update_inventory(line_item.quantity)
        return false
      end
    end
    true
  end

  private def can_user_buy?(deal_id)
    user.ordered_deal_quantity(deal_id) < ORDERS[:max_deal_quant_per_user]
  end

  private def ensure_user_address
    unless address_id && user.addresses.ids.include?(address_id)
      errors.add(:address_id, "has to be of the user #{user.name}")
    end
  end

  private def ensure_payment_made
    if payments.success.blank?
      errors.add(:payment, "no payment with state as succeeded exists")
    end
  end

  private def send_placed_mailer
    if placed?
      OrderMailer.placed(id).deliver_later
    end
  end
end

app/controllers/admin/orders_controller.rb
module Admin
  class OrdersController < AdminController
    before_action :set_order, only: [:shipped, :delivered, :cancel, :show]
    before_action :check_user, only: :index

    def index
      if @user
        @orders = @user.orders.paid_orders
        flash.now[:notice] = "Orders of #{@user.email} found"
      else
        @orders = Order.includes(:user).paid_orders
      end
      @orders = @orders.order(placed_at: :desc, created_at: :desc).page(params[:page]).per(ENV['PER_PAGE_ORDER'].to_i)
    end

    def show
    end

    def shipped
      if @current_order.mark_as_shipped!(params[:note])
        flash.now[:notice] =  "State of Order:#{@current_order.number} updated successfully"
      else
        flash.now[:alert] = "State of Order:#{@current_order.number} could not get updated"
      end
      redirect_back(fallback_location: admin_orders_path)
    end

    def delivered
      if @current_order.mark_as_delivered!(params[:note])
        flash.now[:notice] =  "State of Order:#{@current_order.number} updated successfully"
      else
        flash.now[:alert] = "State of Order:#{@current_order.number} could not get updated"
      end
      redirect_back(fallback_location: admin_orders_path)
    end

    def cancel
      if @current_order.mark_as_cancelled!(params[:note])
        flash[:notice] =  "State of Order:#{@current_order.number} updated successfully"
      else
        flash[:alert] = "State of Order:#{@current_order.number} could not get updated"
      end
      redirect_back(fallback_location: admin_orders_path)
    end

    private def set_order
      @current_order = Order.find_by(id: params[:id])
      if @current_order.blank?
        redirect_to admin_orders_path, alert: "Order could not get retrieved"
      end
    end

    private def check_user
      if params[:user_email].present? && !(@user = User.find_by(email: params[:user_email]))
        redirect_to admin_orders_path, notice: "No user found with email: #{params[:user_email]}"
      end
    end
  end
end

app/controllers/api/orders_controller.rb
module Api
  class OrdersController < ApiBaseController
    before_action :authorize_by_api_token

    def index
        @orders = current_user.orders.paid_orders
        respond_to do |format|
          format.json
          format.html { render plain: 'Invalid URL', status: 422 }
        end
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :ensure_current_order, except: :index
  before_action :ensure_order_in_cart_state, except: [:index, :checkout]
  before_action :ensure_payment_success, only: :checkout
  before_action :ensure_stripe_token_present, only: :charge

  def index
    @orders = current_user.orders.placed_orders.includes([:address, :line_items])
  end

  def add_to_cart
    if current_order.add_item(params[:id])
      flash.now[:notice] = t(".success")
    else
      flash.now[:notice] = t(".failure")
    end
  end

  def rem_from_cart
    if current_order.remove_item(params[:id])
      flash[:notice] = "Deal Removed"
    else
      flash[:alert] = "Deal could not be removed"
    end
    redirect_to home_path
  end

  def buy_now
    unless current_order.update_totals && current_order.save
      redirect_to home_path, notice: "Could not proceed further, please try again"
    end
  end

  def payment
    logger.tagged("Order: payments") { logger.info { "initiating payment for order id: #{current_order.id}" } }
    @current_order = current_order
  end

  def charge
    logger.tagged("Order: payments") do
      logger.info { "Fetched user payment method info(stripeToken) against order id: #{current_order.id}" }

      current_order.transaction do
        if current_order.make_payment(params[:stripeToken])
          logger.info { "Payment process success against order id: #{current_order.id}, redirecting to checkout" }
          redirect_to checkout_orders_path
        elsif current_order.payments.success.present?
          logger.info { "Already a Payment present with success state against order id: #{current_order.id}, redirecting to checkout" }
          redirect_to checkout_orders_path, notice: "A successfull payment already exists against this order"
        elsif current_order.payments.no_success.count <= ENV['MAX_PAYMENT_ATTEMPTS'].to_i
          logger.info { "Payment failed with #{current_order.payments.no_success.count} failed attemts for order id: #{current_order.id},
            trying again and redirecting to buy_now" }
          redirect_to buy_now_orders_path, alert: "Payment failed for some reason, please try again."
        else
          logger.info { "Payment failed with #{current_order.payments.no_success.count} failed attemts for order id: #{current_order.id},
            max failed attempts reached so redirecting to home_path" }
          redirect_to home_path, notice: "Your Order could not get placed, payment failed"
        end
      end
    end
  end

  def checkout
    if current_order.place_order
      session[:order_id] = nil
    else
      redirect_to home_path, notice: "Your Order could not get placed, please try again"
    end
  end

  def select_address
    address = current_user.addresses.find(params[:id])

    if (params[:default] == '1')
      address.default = true
    end

    if address.save && current_order.set_address!(address)
      redirect_to payment_orders_path
    else
      redirect_to buy_now_orders_path, notice: "The address is invalid, please choose another"
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to buy_now_orders_path, notice: "Address could not be found"
  end

  private def create_order
    new_order = current_user.orders.build
    if new_order.save
      session[:order_id] = new_order.id
    end
  end

  private def ensure_current_order
    if !current_order.present?
      create_order
    end
  end

  private def ensure_order_in_cart_state
    if !current_order.cart?
      session[:order_id] = nil
      redirect_to home_path, notice: "Please goto 'my orders' to view your orders"
    end
  end

  private def ensure_payment_success
    if current_order.payments.success.blank? && !current_order.paid?
      redirect_to payment_orders_path, notice: "Please make the payment against your current order"
    end
  end

  private def ensure_stripe_token_present
    if params[:stripeToken].blank?

      logger.tagged("Order: payments") {
        logger.info { "Stripe token blank for order id: #{current_order.id}, redirecting to payment_orders_path" }
      }

      redirect_to payment_orders_path, notice: "Payment could not get processed, please try again"
    end
  end
end

app/views/admin/orders/_orders.html.erb
<div class="container ">
  <table class="table text-center table-striped bg-light">
    <thead class="thead-dark">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Number</th>
        <th scope="col">State</th>
        <th scope="col">Total Amount</th>
        <th scope="col">Total Tax</th>
        <th scope="col">User</th>
        <th scope="col">Items#</th>
        <th scope="col">Placed/Created at</th>
        <th scope="col">Action</th>
      </tr>
    </thead>
    <tbody>
      <% orders.each do |order| %>
        <tr>
          <td><%= order.id %></td>
          <td><%= link_to order.number, admin_order_path(order) %></td>
          <td><%= order.state %></td>
          <td><%= number_to_currency(order.total_amount, unit: '₹') %></td>
          <td><%= number_to_currency(order.total_tax, unit: '₹') %></td>
          <td><%= order.user.email %></td>
          <td><%= order.line_items_count %></td>
          <td><%= order.placed_at&.to_s(:orders) || order.created_at.to_s(:orders) %></td>
          <td><%= link_to "EDIT STATUS", admin_order_path(order) %></td>
        </tr>
      <%end%>
    </tbody>
  </table>
  <div class="container text-center mt-3">
    <%= paginate orders %>
  </div>
</div>

app/views/admin/orders/index.html.erb
<div class="container shadow-lg p-3 mb-5 bg-white rounded">
<div class = "container text-right col-sm mr-3">
  <%= form_with method: :get, local: true, url: admin_orders_path, class: "form-signup" do |form| %>
    <div class = "form-group">
      <%= form.text_field :user_email, placeholder: "Email" %>

      <%= form.submit :SEARCH, class: "btn btn-primary btn-sm" %>

    </div>
  <% end %>
</div>
  <% if @orders.present? %>
    <%= render partial: "orders", locals: { orders: @orders } %>
  <%end%>
  <% #FIXME_AB: what if orders are not present -%>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
   <%= render partial: "orders/order", locals: { order: @current_order } %>
   <div class='container mt-5 text-center'>
      <%if @current_order.placed? %>

        <div class="modal fade" id="shipped-modal" tabindex="-1" role="dialog" aria-labelledby=orderNotes" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Order Notes: <%= @current_order.state %> => <span class="text-info">SHIPPED</span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <%= form_with(method: 'get', local: true, url: shipped_admin_order_path(@current_order)) do |f| %>
                  <div class="form-group">
                    <%= f.text_area :note, placeholder: "Order Note", class: 'form-control', id: "message-text", rows: 5, cols: 30   %>
                  </div>
                  <div class="modal-footer">
                    <%= f.submit :SUBMIT, class: "btn btn-primary" %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>

        <%= link_to "SHIPPED", "#", data: {toggle: "modal", target: "#shipped-modal"}, class: "btn btn-lg btn-info ml-5" %>

    <%end%>

    <%if @current_order.placed? || @current_order.shipped? %>

        <div class="modal fade" id="delivered-modal" tabindex="-1" role="dialog" aria-labelledby=orderNotes" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Order Notes: <%= @current_order.state %> => <span class="text-success">DELIVERED</span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <%= form_with(method: 'get', local: true, url: delivered_admin_order_path(@current_order)) do |f| %>
                  <div class="form-group">
                    <%= f.text_area :note, placeholder: "Order Note", class: 'form-control', id: "message-text", rows: 5, cols: 30   %>
                  </div>
                  <div class="modal-footer">
                    <%= f.submit :SUBMIT, class: "btn btn-primary" %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>

        <div class="modal fade" id="cancel-modal" tabindex="-1" role="dialog" aria-labelledby=orderNotes" aria-hidden="true">
          <div class="modal-dialog modal-dialog-centered modal-lg">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Order Notes: <%= @current_order.state %> => <span class="text-danger">CANCEL</span></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
              <div class="modal-body">
                <%= form_with(method: 'get', local: true, url: cancel_admin_order_path(@current_order)) do |f| %>
                  <div class="form-group">
                    <%= f.text_area :note, placeholder: "Order Note", class: 'form-control', id: "message-text", rows: 5, cols: 30   %>
                  </div>
                  <div class="modal-footer">
                    <%= f.submit :SUBMIT, class: "btn btn-primary" %>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>


        <%= link_to "DELIVERED", "#", data: {toggle: "modal", target: "#delivered-modal"}, class: "btn btn-lg btn-success ml-5" %>
        <%= link_to "CANCEL", "#", data: {toggle: "modal", target: "#cancel-modal"}, class: "btn btn-lg btn-danger ml-5" %>
<%
=begin%>

        <%= link_to "", delivered_admin_order_path(@current_order), class: "btn btn-lg btn-success ml-5" %>
        <%= link_to "", cancel_admin_order_path(@current_order), class: "btn btn-lg btn-danger ml-5" %>
<%
=end%>
    <%end%>


   </div>
</div>