config/routes.rb
Rails.application.routes.draw do
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout'  => :destroy
  end

  # // for time being lets open letter opener for all envs
  mount LetterOpenerWeb::Engine, at: "/letter_opener" #if Rails.env.development?

  root 'home#index', as: 'home'
  get "homepage_poll", to: 'home#poll'
  get "verify/:token", action: :verify, controller: :users, as: 'verify'

  resources :users, only: [:new, :create] do
    get "my_profile", on: :collection
  end

  resources :password_resets, only: [:new, :create, :edit, :update], param: :token

  resources :addresses, only: [:create, :new]
  resources :orders, only: :index do
    collection do
      get "buy_now"
      get "payment"
      post "charge"
      get "checkout"
    end
    member do
      get "add_to_cart"
      delete "rem_from_cart"
      get "select_address"
    end
  end

  namespace :admin do
    get "/", to: "deals#index"
    get 'top_customers', to: "users#top_customers"
    resources :deals do
      member do
        get "check_publishability"
        get "delete_image_attachment"
        get "publish"
        get "unpublish"
      end
    end
    resources :orders, only: [:index, :show] do
      member do
        get "cancel"
        get "shipped"
        get "delivered"
      end
    end
  end

  namespace :api do
    get 'deals/live', to: 'deals#live' 
    get 'deals/past', to: 'deals#past' 
    get 'myorders/:token', to: 'orders#index'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id               :bigint           not null, primary key
#  total_amount     :decimal(, )
#  total_tax        :decimal(, )
#  address_id       :bigint
#  user_id          :bigint           not null
#  deleted_at       :datetime
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  state            :integer          default("cart"), not null
#  line_items_count :integer
#  placed_at        :datetime
#
class Order < ApplicationRecord
  enum state: {
    cart: 0,
    paid: 1,
    placed: 2,
    shipped: 3,
    delivered: 4,
    cancelled: 5,
    refunded: 6
  }

  acts_as_paranoid
  define_model_callbacks :place_order, :mark_shipped, :mark_delivered, :mark_cancelled, only: :after

  validate :ensure_user_address, :ensure_payment_made, if: -> { placed? || shipped? || delivered? }
  validates :line_items_count, numericality: { greater_than: 0 }, if: -> { placed? }
  validate :ensure_state_transition, if: -> { state_change }

  has_many :line_items, dependent: :destroy
  has_many :deals, through: :line_items
  has_many :payments, dependent: :destroy
  has_many :order_histories, dependent: :destroy
  belongs_to :user
  belongs_to :address, optional: true

  after_place_order :send_placed_mailer
  after_mark_shipped :state_shipped
  after_mark_delivered :state_delivered
  after_mark_cancelled :state_cancelled

  scope :placed_orders, ->{ where(state: :placed).or where(state: :shipped).or where(state: :delivered) }
  scope :paid_orders, -> { where.not(state: :cart) }
  scope :shipped, -> { where(state: :shipped) }
  scope :delivered, -> { where(state: :delivered) }

  def number
   "#{(placed_at || created_at).to_s(:number)}-#{id}"
  end

  def add_item(deal_id)
    deal = Deal.live_deals(Time.current).find_by(id: deal_id)
    deal.present? && deal.saleable_qty_available? && can_user_buy?(deal.id) && (item = line_items.create(deal: deal, quantity: LINEITEMS[:default_quantity])) && item.persisted?
  end

  def remove_item(line_item_id)
    line_items.find_by(id: line_item_id)&.destroy
  end

  def place_order
    run_callbacks :place_order do
      unless paid?
        return false
      end

      line_items.includes(:deal).each do |line_item|
        unless line_item.deal.live? || can_user_buy?(line_item.deal_id) || line_item.deal.check_inventory(line_item.quantity)
          return false
        end
      end

      transaction do
        if update_inventory
          self.state = self.class.states[:placed]
          self.placed_at = Time.current
          #FIXME_AB: use create! here so that it raise an eception if failed and transaction rollbacks, same at other places
          save! && order_histories.create!(state: state, note: "Order Placed")
        else
          raise StandardError.new "Update Inventory Failure"
          return false
        end
      end
    rescue StandardError
      logger.tagged("Order: payments[refund]") do
        if process_refunds
          logger.info { "Order state changed to: #{state}, sending refund_intimation mailer" }
          OrderMailer.refund_intimation(id).deliver_later
        end
      end
    false
    end
  end


  def process_refunds
    transaction do
      if payments.success.map(&:refund).all?{ |refund_status| refund_status}
        logger.info { "Refund process success, updating order state to refund state" }
        order_histories.create!(state: state, note: "Refund success")
        update(state: self.class.states[:refunded])
      else
        logger.info { "some payments could not be refunded" }
      end
    end
  end

  def set_address!(address)
    self.address = address
    save
  end

  def update_totals
    self.total_amount = line_items.sum(&:sub_total)
    self.total_tax = line_items.sum(&:sub_tax_total)
  end

  def make_payment(token)
    logger.info { "initiating make_payment method against order id: #{id}, calling stripe_transact after checks & building payment" }
    paid = self.class.states[:paid]
    cart? && address && payments.build.stripe_transact(token) && update(state: paid) && order_histories.create!(state: paid, note: "Payment success")
  end

  def mark_as_shipped!(note)
    transaction do
      run_callbacks :mark_shipped do
        self.state = Order.states[:shipped]
        save && (event = order_histories.create!(state: state, note: note)) && event.persisted?
      end
    end
  end

  def mark_as_delivered!(note)
    transaction do
      run_callbacks :mark_delivered do
        self.state = Order.states[:delivered]
        save && (event = order_histories.create!(state: state, note: note)) && event.persisted?
      end
    end
  end

  def mark_as_cancelled!(note)
    transaction do 
      run_callbacks :mark_cancelled do
        self.state = Order.states[:cancelled]
        save && process_refunds && (event = order_histories.create!(state: state, note: note)) && event.persisted?
      end
    end
  end

  private def state_shipped
    if shipped?
      OrderMailer.shipped(id).deliver_later
    end
  end

  private def state_delivered
    if delivered?
      OrderMailer.delivered(id).deliver_later
    end
  end

  private def state_cancelled
    if refunded?
      OrderMailer.refund_intimation(id).deliver_later
    end
  end

  private def ensure_state_transition
    if !(STATE_TRASITIONS[state_was].include?(state))
      errors.add(:state, "transition from #{state_was} to #{state} is not allowed")
    end
  end

  private def update_inventory
    line_items.each do |line_item|
      unless line_item.deal.update_inventory(line_item.quantity)
        return false
      end
    end
    true
  end

  private def can_user_buy?(deal_id)
    user.ordered_deal_quantity(deal_id) < ORDERS[:max_deal_quant_per_user]
  end

  private def ensure_user_address
    unless address_id && user.addresses.ids.include?(address_id)
      errors.add(:address_id, "has to be of the user #{user.name}")
    end
  end

  private def ensure_payment_made
    if payments.success.blank?
      errors.add(:payment, "no payment with state as succeeded exists")
    end
  end

  private def send_placed_mailer
    if placed?
      OrderMailer.placed(id).deliver_later
    end
  end
end

app/controllers/admin/home_controller.rb
module Admin
  class HomeController < AdminController

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authorize

  def index
    @live_deals = Deal.live_deals(Time.current).with_attached_images
    @past_deals = Deal.with_attached_images.past_live(ENV["PAST_LIVE_DEALS_SHOW"].to_i)
  end

  def poll
    live_deals = Deal.live_deals(Time.current)
    live_deals = live_deals.present? ? live_deals.pluck(:id, :live_end).to_json : nil

    render json: { live_deals: live_deals }
  end
end

app/views/home/_deals.html.erb
<% deals.each do |deal| %>
  <div class="row" data-deal_id = <%= deal.id %>>
    <div class="col">
      <div class = "card bg-light mb-4 shadow-lg p-3 mb-5 bg-light rounded">
        <div class = "card-header bg-dark">
          <div id="carouselExampleControls<%=deal.id%>" class="carousel slide" data-ride="carousel">
            <div class="carousel-inner">
              <% if deal.images.attached? %>
                <% deal.images.each_with_index do |image, index| %>
                  <div class = "carousel-item <%= if index == 0; "active"; end %> id = "slide <%= index + 1 %>">
                    <%= image_tag(url_for(image), class: "rounded mx-auto d-block img-fluid thumbnail") %>
                  </div>
                <% end %>
              <% end %>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleControls<%=deal.id%>" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="false"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleControls<%=deal.id%>" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
        <div class = "card-body bg-secondary">
          <h5 class="card-title text-center text-white bg-dark rounded"><%= deal.title %></h5>
          <div class="row">
            <div class="col">
              <p>
                <strong>Description:</strong>
                <%= deal.description %>
              </p>
              <p>
                <strong>Price:</strong>
                <%= number_to_currency(deal.price, unit: '₹') %>
              </p>
              <p>
                <strong>Discount:</strong>
                <%= number_to_currency(deal.discount_price, unit: '₹') %>
              </p>
              <p>
                <strong>Original Quantity:</strong>
                <%= deal.quantity %>
              </p>
              <p>
                <strong>Deal Tax:</strong>
                <%= deal.tax %>
              </p>
            </div>
          </div>
          <% if current_user.present? && deal.live?%>
            <% if deal.saleable_qty_available? %>
              <%= link_to "Add To CART", add_to_cart_order_path(deal), class: "btn btn-warning add-to-cart-btn", remote: true  %>
            <% else %>
              <div class=" border rounded border-white bg-danger text-white text-center">SOLD OUT</div>
            <% end %>
          <%end%>
        </div>
        <br>
      </div>
    </div>
  </div>
<% end %>

app/views/home/index.html.erb
<div class = "container shadow-lg p-3 mb-5 bg-white rounded">
<% if @live_deals.present? %>
    <% content_for :js do %>
      <%= javascript_pack_tag  'show_past_deals', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag  'deals_home_polling', 'data-turbolinks-track': 'reload' %>
    <%end%>
  <% end %>
  <div class = "cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
    <header class = "masthead mb-auto">
      <div class = "inner">
        <h1 class = "masthead-brand text-center"> Flash Sale Welcome !!! </h1>
      </div>
    </header>
    <main class = "inner cover" role = "main">
    <h3 class="cover-heading text-center">
      <% if @live_deals.present? %>
        <% deals = @live_deals %>
        LIVE DEALS
      <% else %>
        <% deals = @past_deals %>
        PAST DEALS
      <% end %>
    </h3>
    <div class="container bg-info border border-dark rounded" id="cart">
      <% if should_display_cart?(current_order) %>
        <%= render partial: 'orders/cart' %>
      <% end %>
    </div>
    <br>
    <div id="deals-home" data-url = <%= homepage_poll_url%> data-deal_ids = "<%= deals.collect(&:id) %>">
      <%= render partial: "deals", locals: { deals: deals } %>
    </div>
    <% if @live_deals.present? && @past_deals.present? %>
      <div class="container text-center">
        <%= link_to "Show Past Deals", home_path, remote: true, class: "btn btn-outline-info mb-3" , id: "past-deals-btn",
          data: { past_deals: (render partial: "deals", locals: { deals: @past_deals }) }%>
      </div>
      <div id="past-deals-div">
      </div>
    <% end %>
    </main>
    <footer class = "mastfoot mt-auto">
      <div class = "inner text-center">
        <p>2020 </p>
      </div>
    </footer>
  </div>
</div>