config/routes.rb
Rails.application.routes.draw do
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout'  => :destroy
  end

  # // for time being lets open letter opener for all envs
  mount LetterOpenerWeb::Engine, at: "/letter_opener" #if Rails.env.development?

  root 'home#index', as: 'home'
  get "homepage_poll", to: 'home#poll'
  get "verify/:token", action: :verify, controller: :users, as: 'verify'

  resources :users, only: [:new, :create] do
    get "my_profile", on: :collection
  end

  resources :password_resets, only: [:new, :create, :edit, :update], param: :token

  resources :addresses, only: [:create, :new]
  resources :orders, only: :index do
    collection do
      get "buy_now"
      get "payment"
      post "charge"
      get "checkout"
    end
    member do
      get "add_to_cart"
      delete "rem_from_cart"
      get "select_address"
    end
  end

  namespace :admin do
    get "/", to: "deals#index"
    get 'top_customers', to: "users#top_customers"
    resources :deals do
      member do
        get "check_publishability"
        get "delete_image_attachment"
        get "publish"
        get "unpublish"
      end
    end
    resources :orders, only: [:index, :show] do
      member do
        get "cancel"
        get "shipped"
        get "delivered"
      end
    end
  end

  namespace :api do
    get 'deals/live', to: 'deals#live' 
    get 'deals/past', to: 'deals#past' 
    get 'myorders/:token', to: 'orders#index'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/deal.rb
# == Schema Information
#
# Table name: deals
#
#  id             :bigint           not null, primary key
#  title          :citext           not null
#  description    :text
#  price          :decimal(8, 2)
#  discount_price :decimal(8, 2)    default(0.0), not null
#  quantity       :integer          default(0), not null
#  published_at   :datetime
#  deleted_at     :datetime
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  live_begin     :datetime
#  live_end       :datetime
#  tax            :decimal(, )
#  sold_quantity  :integer          default(0), not null
#  lock_version   :integer          default(0), not null
#
class Deal < ApplicationRecord

  include BasicPresenter::Concern
  acts_as_paranoid


  validates :title, :description, presence: true
  validates :price, presence: true, numericality: { greater_than: 0 }
  validates :discount_price, numericality: { only_decimal: true, greater_than_or_equal_to: 0 }
  validates :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :quantity, numericality: {  greater_than: 0 }, if: -> { published_at.present? }
  validates :title, uniqueness: true, case_sensitive: false, if: -> { title.present? }
  validates :tax, numericality: { only_decimal: true }, inclusion: { in: DEALS[:min_tax_allowed]..DEALS[:max_tax_allowed],
             message: "should lie between #{DEALS[:min_tax_allowed]} and #{DEALS[:max_tax_allowed]}"}, allow_nil: true,
             format: { with: REGEXPS[:tax], message: "can have max 4 decimal places" }
  validate :ensure_image_format, if: -> { images.present? }
  validate :ensure_min_image_upload

  validates_with PriceValidator

  has_many_attached :images, dependent: :purge_later
  has_many :line_items, dependent: :restrict_with_error
  has_many :orders, through: :line_items

  before_save :ensure_publishability_criteria, if: -> { published_at.present? }
  scope :published_on, ->(date) { where(published_at: date.beginning_of_day..date.end_of_day) }
  scope :past_live, ->(quantity) { where('published_at < ?', Time.current - 1.day).order(:published_at).last(quantity) }
  scope :live_deals, ->(datetime) { where('live_begin <= :lookup_time AND live_end >= :lookup_time', { lookup_time: datetime }) }
  scope :past_deals, ->(datetime) { where("live_end < ?", datetime) }

  def can_be_scheduled_to_publish_on(date)
    #FIXME_AB: need to consider current deal
    if published_at&.to_date == date
      return true
    end
    valid? && (self.class.published_deals_on(date) < DEALS[:max_deals_per_day]) &&
    (date > Date.today + 1.day)
  end

  def self.published_deals_on(date)
    published_on(date).count
  end

  def live?
    self.class.live_deals(Time.current).exists? self.id
  end

  def live!
    if published_at&.today?
      time_now = Time.current
      update_columns(live_begin: time_now, live_end: time_now + ENV["DEAL_LIVE_DAYS"].to_i.day)
    end
  end

  def gross_revenue
    #FIXME_AB: this can be done a better way. you are selecting all line items and then selecting items based on order's status. Should be other way around
    line_items.includes(:order).select{|line| line.order && (line.order.placed? || line.order.shipped? || line.order.delivered?) }.collect(&:sub_total).sum
  end

  #FIXME_AB: this calculation is wrong
  def max_potential
    price - discount_price
  end

  #FIXME_AB: this calculation is wrong
  def min_potential
    max_potential - ((USERS[:max_orders_count_for_discount].to_f/100) * max_potential)
  end

  def saleable_qty_available?
    salebale_qty.positive?
  end

  def salebale_qty
    quantity - sold_quantity
  end

  def check_inventory(qty_bought)
    saleable_qty_available? && qty_bought <= salebale_qty
  end

  def update_inventory(qty_bought)
    if check_inventory(qty_bought)
      sold_quantity = self.sold_quantity + qty_bought
      self.update_columns(sold_quantity: sold_quantity, lock_version: lock_version + 1, updated_at: Time.current)
    else
      false
    end
  rescue StandardError
    false
  end

  def publish(date)
    publish_on_date = Date.parse(date)
    if publish_on_date.present? && can_be_scheduled_to_publish_on(publish_on_date)
      self.published_at = publish_on_date
      save
    else
      false
    end
  rescue StandardError
    false
  end

  def can_be_rescheduled? # or we can do .save? {ensure_publishability_criteria}
    published_at && published_at > Time.current + ENV['PUBLISH_DEAL_RESTRICT_TIME'].to_i.day && !live?
  end

  def can_be_updated?
    published_at.blank? || can_be_rescheduled?
  end

  def unpublish
    if can_be_rescheduled?
      self.published_at = nil
      save
    else
      false
    end
  end

  private def ensure_image_format
    if images.any? { |img| !img.image? }
      errors.add(:images, "#{I18n.t("errors.file_format")}")
    end
  end

  private def ensure_min_image_upload
    if images.count < DEALS[:min_images_limit]
      errors.add(:images, "#{I18n.t("errors.image")} #{DEALS[:min_images_limit]}")
    end
  end

  private def ensure_publishability_criteria
    #FIXME_AB: we should also check that if publish_at is changed then its previous publish date should not be in past day

    #FIXME_AB: in case of updating the deal which is scheduled to publish on specific day, it will fail
    #FIXME_AB: make a method for every condition can_be_scheduled_to_publish_on?(date) && valid_qty_available? && valid_publish_date_margin
    unless can_be_scheduled_to_publish_on? && valid_qty_availaible? && is_tax_present? && valid_publish_date_margin?
    raise UnPublishableError.new "Publishability criteria failed"
    end
  end


  private def can_be_scheduled_to_publish_on?
    if self.class.exists?(id) && self.class.find(id).published_at&.to_date == published_at.to_date
      current_published_deal =  1
    end
    self.class.published_deals_on(published_at) - (current_published_deal || 0) <= (DEALS[:max_deals_per_day] - 1)
  end

  private def is_tax_present?
    tax.present?
  end

  private def valid_qty_availaible?
    quantity >= DEALS[:min_quant_limit]
  end

   private def valid_publish_date_margin?
    existing_deal = self.class.find_by(id: id)
    if existing_deal&.published_at&.present?
      if existing_deal.published_at.to_date <= (Time.current + ENV['PUBLISH_DEAL_RESTRICT_TIME'].to_i.day).to_date ||
         existing_deal.published_at.to_date != published_at.to_date && published_at.to_date < (Date.today + 1.day)
        return false
      end
    elsif published_at.to_date < (Date.today + 1.day)
      return false
    end
    true
  end

end

app/controllers/admin/deals_controller.rb
module Admin
  class DealsController < AdminController
    before_action :set_deal, only: [:show, :edit, :update, :destroy, :check_publishability, :publish, :unpublish]
    before_action :ensure_editable, only: :edit

    def index
      sort_by = (params[:sort] && params[:sort][:sort_by].present?) ? params[:sort][:sort_by] : 'published_at'
      order = (params[:order] && params[:order][:order_by].present?) ? params[:order][:order_by] : 'asc'
      @deals = Deal.with_attached_images.order("#{sort_by} #{order}")
                   .page(params[:page]).per(ENV["PER_PAGE_DEAL"].to_i)
    end

    def new
      @deal = Deal.new
    end

    def create
      @deal = Deal.new(deal_params)
      respond_to do |format|
        if @deal.save
          format.html { redirect_to admin_deal_path(@deal), notice: t(".flash.success")}
        else
          format.html { render :new }
        end
      end
    end

    def edit
    end

    def update
      respond_to do |format|
        if @deal.update(deal_params)
          format.html { redirect_to admin_deal_path(@deal), notice: t(".flash.success") }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      if @deal.destroy
        flash[:notice] = t(".flash.success")
      else
        flash[:error] = "#{t(".flash.failure")} #{@deal.errors[:base][0]}"
      end
      redirect_to admin_deals_path
    end

    def check_publishability
      if params[:publishable_check_date]
        @status = @deal.can_be_scheduled_to_publish_on(Date.parse(params[:publishable_check_date]))
      end
    end

    def publish
      render json: { status: @deal.publish(params[:publish_date]), publish_presenter: @deal.presenter.publish_status }
    end

    def unpublish
      if @deal.unpublish
        flash[:notice] = "Deal #{@deal.title} unscheduled succsssfully"
      else
        flash[:alert] = "Deal could not get unscheduled"
      end
      redirect_to admin_deal_path(@deal.id)
    end

    def delete_image_attachment
      @deal_image = ActiveStorage::Attachment.find(params[:id])
      @deal_image.purge_later
      render json: { status: true }
    rescue ActiveRecord::RecordNotFound
      render json: { status: false }
    end

    private def deal_params
      params.require(:deal).permit(:title, :description, :price, :discount_price,
                                   :quantity, :tax, images: [])
    end

    private def set_deal
      @deal = Deal.with_attached_images.find(params[:id])
      if @deal.blank?
        redirect_to login_path, notice: "Please login again"
      end
    end

    private def ensure_editable
      if !@deal.can_be_updated?
        redirect_to admin_deals_path, notice: "Deal #{@deal.title} cannot be updated at this stage"
      end
    end

  end
end

app/controllers/api/deals_controller.rb
module Api
  class DealsController < ApiBaseController
    def live
      @live_deals = Deal.live_deals(Time.current)
      respond_to do |format|
        format.json
        format.html { render plain: 'invalid url' }
      end
    end

    def past
      @past_deals = Deal.past_deals(Time.current)
      respond_to do |format|
        format.json
        format.html { render plain: 'invalid url' }
      end
    end
  end
end

app/views/admin/deals/_form.html.erb
<div class = "container shadow-lg p-3 mb-5 bg-white rounded">
  <% content_for :js do %>
    <%= javascript_pack_tag  'deal_form_images', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag  'deal_remove_image', 'data-turbolinks-track': 'reload' %>
  <% end %>
<div class = 'row container'>
  <%= form_with(model: deal, url: deal_path, local: true, class: "form-signin", id: "deals-form") do |form| %>
    <%= render partial: 'shared/errors', locals:{ object: deal } %>

    <h4> Enter Deal Details </h4>

    <div class = "form-group">
      <%= form.label :title, "Title:" %>
      <%= form.text_field :title, placeholder: "Title", class: 'form-control' %>
    </div>

    <div class = "form-group">
      <%= form.label :description, "Description:" %>
      <%= form.text_area :description, placeholder: "Description", class: 'form-control', rows: 5, cols: 30  %>
    </div>

    <div class = "form-group">
      <%= form.label :price, "Price:" %>
      <%= form.text_field :price, placeholder: "Price", class: 'form-control' %>
    </div>

    <div class = "form-group">
      <%= form.label :discount_price, "Discount:" %>
      <%= form.text_field :discount_price, placeholder: "Discount_price", class: 'form-control' %>
    </div>

    <div class = "form-group">
      <%= form.label :quantity, "Quantity:" %>
      <%= form.text_field :quantity, placeholder: "Quantity", class: 'form-control' %>
    </div>

    <div class = "form-group">
      <%= form.label :tax, "Tax (%):" %>
      <%= form.text_field :tax, placeholder: "Tax (in %)", class: 'form-control' %>
    </div>
    <% if deal.images.present? %>
        <% deal.images.each do |image| %>
          <% if image.id %>
            <div class="container text-center border border-primary rounded ">
              <%= image_tag(url_for(image), class: "rounded mx-auto img-thumbnail thumbnail mt-3") %>
              <h4><%= image.blob.filename %> </h4>
              <br>
              <%= link_to 'Remove', delete_image_attachment_admin_deal_url(image),
                            data: {  url: delete_image_attachment_admin_deal_url(image) },
                            class: "btn btn-outline-danger mb-3 deal-img-rem" %>
            </div>
          <%end%>
          <br>
        <%end%>
      </div>
    <%end%>

    <%= render 'image_fields', f: form %>
    <%= link_to_add_fields "Add more", form, "images" %>

    <div class = "form-group">
    <br>
    <%if deal.persisted? %>
      <%= form.submit :SAVE, class: "btn btn-primary" %>
    <% else %>
      <%= form.submit :CREATE, class: "btn btn-primary" %>
    <% end %>
      <%= link_to :CANCEL, admin_deals_path,  class: "btn btn-primary"  %>
    </div></div>

  <% end %>
</div>

app/views/admin/deals/_image_fields.html.erb
<div class = "form-group">
  <%= f.label :images, "Images:" %>
  <%= f.file_field :images, multiple: true  %>
</div>

app/views/admin/deals/check_publishability.js.erb
publishStateDiv = document.getElementById("check-publish-data")

<% if @status %>
  publishStateDiv.innerHTML = "<strong> Publishable </strong>"
  publishStateDiv.className = "bg-success text-center border"
<% else %>
  publishStateDiv.innerHTML = "<strong> NOT Publishable </strong >"
  publishStateDiv.className = "bg-danger text-center border"
<%end%>

app/views/admin/deals/edit.html.erb
<div class="container">
  <h1> Edit Deal </h1>
</div>

<%= render "form", deal: @deal, deal_path: admin_deal_path(@deal) %>

app/views/admin/deals/index.html.erb
<div class = "container text-right col-sm">
  <%= form_with method: :get, local: true, url: admin_deals_path, class: "form-signup" do %>
    <div class = "form-group">
      <%= select(:sort, :sort_by, options_for_select([['created_at', 'created_at'], ['published_at', 'published_at']],selected: params[:sort] ? params[:sort][:sort_by] : 'published_at'), {}, { onchange: 'this.form.submit();'}) %>
      <%= select(:order, :order_by, options_for_select([['asc', 'ASC'], ['desc', 'DESC']], selected: params[:order] ? params[:order][:order_by] : 'ASC'), {}, { onchange: 'this.form.submit();'}) %>
    </div>
  <% end %>
</div>
<div class="container shadow-lg p-3 mb-5 bg-white rounded">
  <div class="row ml-5">
    <% @deals.to_enum.with_index(1).each do |deal, index| %>

      <%if index % 3 == 0%>
        </div>
        <div class="row ml-5">
      <% end%>

      <div class="col-md-6 d-flex align-items-stretch col-lg-6">
        <div class = "card text-dark bg-light mb-3 shadow-lg" style="width: 80%;">
          <div class = "card-header text-center bg-light">
            <%if deal.images.attached? %>
              <% image = deal.presenter.cover_image %>
              <div class="col text-center">
                <%= image_tag( url_for(image), class: "rounded img-thumbnail thumbnail" ) %>
              </div>
            <% end %>
          </div>


            <div class = "card-body ">
              <h5 class="card-title text-white bg-dark text-center rounded"><%= deal.title %></h5>
              <p> <strong>Price:</strong>
                <%= number_to_currency(deal.price, unit: '₹') %>
              </p>
              <p> <strong>Publishable:</strong>
                <%= deal.presenter.publish_status %>
              </p>

              <table class="table text-white">
                <tbody>
                  <tr>
                    <td> <%= link_to "EDIT", edit_admin_deal_path(deal), class: "btn btn-primary btn-block" %> </td>
                    <td> <%= link_to "SHOW", admin_deal_path(deal), class: "btn btn-primary btn-block" %> </td>
                    <td> <%= link_to "DESTROY", admin_deal_path(deal), method: :delete, class: "btn btn-danger btn-block",
                                     data: { confirm: "Are you sure to delete deal with title #{deal.title}?" } %> </td>
                  </tr>
                </tbody>
              </table>

            </div>
            <br>
        </div>
      </div>
    <% end %>

    <div class="container text-center mt-3">
      <%= paginate @deals %>
    </div>
  </div>
</div>

app/views/admin/deals/new.html.erb
<%= render "form", deal: @deal, deal_path: admin_deals_path%>

app/views/admin/deals/show.html.erb
<div class = "container ">
  <% content_for :js do %>
    <%= javascript_pack_tag  'deal_publish', 'data-turbolinks-track': 'reload' %>
  <% end %>
  <div class = "card text-black bg-light shadow-lg border rounded" style="width: 80%;">
    <div class = "card-header bg-dark">
      <% if @deal.images.attached? %>
        <div class="row">
          <% @deal.images.each_with_index do |image, index| %>
            <%if index % 3 == 0 && index != 0%>
              </div>
              <div class="row">
            <% end%>
            <div class = "col">
              <%= image_tag(url_for(image), class: "rounded mx-auto img-thumbnail thumbnail") %>
              <br>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class = "card-body">
      <p>
        <strong>Title:</strong>
        <%= @deal.title %>
      </p>
      <p>
        <strong>Description:</strong>
        <%= @deal.description %>
      </p>
      <p>
        <strong>Price:</strong>
        <%= number_to_currency(@deal.price, unit: '₹') %>
      </p>
      <p>
        <strong>Publishable:</strong>
        <h5 id = "publish-date"><%= @deal.presenter.publish_status %></h5>
      </p>

      <div id = "check-publish-data">
      </div>

      <br>
      <% if @deal.published_at.blank? || @deal.can_be_rescheduled? %>
        <div class = "container text-center mb-5">
          <%= form_with method: :get, url: check_publishability_admin_deal_path, class: "form-signin" do %>

            <div class = "form-group">
              <%= date_field_tag(:publishable_check_date, class: "form-date") %>
            </div>
            <div class = "form-group">
              <%= submit_tag "Check Publishability", class: "btn btn-info" %>
            </div>

          <%end%>
        </div>
        <div id = "publish-data">
        </div>
        <div class = "container text-center col">
          <%= form_with method: :get, url: publish_admin_deal_path, class: "form-signin", id: "publish-form" do %>

            <div class = "form-group">
              <%= date_field_tag(:publish_date, class: "form-date") %>
            </div>
            <div class = "form-group">
              <% if @deal.published_at.blank? %>
                <%= submit_tag "Schedule", class: "btn btn-warning btn-lg", id: "publish-btn", data: { unpublish_url: unpublish_admin_deal_url, disable_with: "Please wait..."  }  %>
                <%= submit_tag "Re Schedule", class: "btn btn-warning btn-lg", id: "republish-btn", data: { unpublish_url: unpublish_admin_deal_url, disable_with: "Please wait..."  }  %>
              <% else %>
                <%= submit_tag "Re Schedule", class: "btn btn-warning btn-lg" %>
                </div>
                <div class = "container">
                <%= link_to "Remove Schedule", unpublish_admin_deal_path, class: "btn btn-danger", id: "unschedule-deal",
                    data: { confirm: "Are you sure ?" } %>
              <% end %>
            </div>

          <%end%>
        </div>
      <% end %>
      <div class="container text-center">
      <button type="button" class="btn btn-lg btn-primary deal-report-btn">Show Report</button>
      </div>
      <div class="row deal-report">
        <div class="card col-md-12 shadow-lg border rounded">
          <div class="card-body">
            <h4 class="card-title">
              <%= @deal.title %>(<%= @deal.id %>)
              <span class='float-right text-uppercase'>
              <% deal_publish_status = @deal.presenter.publish_status %>
              <% if @deal.published_at.blank? %>
                <span class='text-danger'><%= deal_publish_status %></span>
              <% else %>
                <span class='text-success'><%= deal_publish_status %></span>
              <% end %>
              </span>
            </h4>
            <h6 class="card-subtitle mb-2 text-muted"><%= @deal.description %></h6>
            <div class="mt-5 float-right">
              <button type="button" class="btn btn-warning">
                Discount <span class="badge badge-light"><%= number_to_currency(@deal.discount_price, unit: '₹') %></span>
              </button>
              <button type="button" class="btn btn-success">
                Price <span class="badge badge-light"><%= number_to_currency(@deal.price, unit: '₹') %></span>
              </button>
            </div>
            <p class="card-text">
              <h3 class = 'mt-5'>Reports:</h3>
              <div class="clearfix"></div>
              <br>
              <button type="button" class="btn btn-primary btn-lg text-center">
                GROSS REVENUE <span class="badge badge-light"><%= number_to_currency(@deal.gross_revenue, unit: '₹') %></span>
              </button>
              <div class="float-right">
                <button type="button" class="btn btn-light btn-md">
                  MAX Potential <span class="badge badge-light"><%= number_to_currency(@deal.max_potential, unit: '₹') %></span>
                </button>
                <button type="button" class="btn btn-dark btn-md text-color-light">
                  MIN Potential <span class="badge badge-light"><%= number_to_currency(@deal.min_potential, unit: '₹') %></span>
                </button>
              </div>
            </p>
          </div>
        </div>
      </div>


    </div>
  </div>
  <br>
  <%= link_to "Back", admin_deals_path %>
</div>

app/views/admin/deals/show.js.erb
publishStateDiv = document.getElementById("publish-data")

<% if @status %>
  publishStateDiv.innerHTML = "The Deal is publishable"
<% else %>
  publishStateDiv.innerHTML = "The Deal is NOT publishable"
<%end%>