config/routes.rb
Rails.application.routes.draw do
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout'  => :destroy
  end

  # // for time being lets open letter opener for all envs
  mount LetterOpenerWeb::Engine, at: "/letter_opener" #if Rails.env.development?

  root 'home#index', as: 'home'
  get "homepage_poll", to: 'home#poll'
  get "verify/:token", action: :verify, controller: :users, as: 'verify'

  resources :users, only: [:new, :create] do
    get "my_profile", on: :collection
  end

  resources :password_resets, only: [:new, :create, :edit, :update], param: :token

  resources :addresses, only: [:create, :new]
  resources :orders, only: :index do
    collection do
      get "buy_now"
      get "payment"
      post "charge"
      get "checkout"
    end
    member do
      get "add_to_cart"
      delete "rem_from_cart"
      get "select_address"
    end
  end

  namespace :admin do
    get "/", to: "deals#index"
    get 'top_customers', to: "users#top_customers"
    resources :deals do
      member do
        get "check_publishability"
        get "delete_image_attachment"
        get "publish"
        get "unpublish"
      end
    end
    resources :orders, only: [:index, :show] do
      member do
        get "cancel"
        get "shipped"
        get "delivered"
      end
    end
  end

  namespace :api do
    get 'deals/live', to: 'deals#live' 
    get 'deals/past', to: 'deals#past' 
    get 'myorders/:token', to: 'orders#index'
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlashSaleSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'ajax_loader', 'data-turbolinks-track': 'reload' %>
    <%= yield :js %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href= <%= admin_deals_path %> >
      <img src= <%= image_path 'flash-sale-logo-navbar.jpg' %> width="130" height="80" alt=""></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href= <%= home_path %> >Home <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" href= <%= admin_orders_path %> >Orders</a>
          <a class="nav-item nav-link" href= <%= admin_deals_path %> >Deals</a>
          <a class="nav-item nav-link" href= <%= new_admin_deal_path %> >New Deal</a>      
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Reports</a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <a class="dropdown-item" href=<%= admin_top_customers_path%>>Top Customers</a>
            </div>
          </li>
          <%= link_to "SignOut", logout_path, method: :delete, class: "nav-item nav-link" %>
        </div>
      </div>
    </nav>
    <br>
    <% flash_bootstrap_class = {
      'alert' => 'alert-warning',
      'notice' => "alert-success",
      'error' => "alert-danger"
    } %>
    <div class = "site-wrapper">
      <div class = "text-center" id="flash">
        <% flash.each do |type| %>
          <aside class = "alert <%=  flash_bootstrap_class[type[0]] %>" > <%= type[1] %></aside>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlashSaleSite</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'ajax_loader', 'data-turbolinks-track': 'reload' %>
    <%= yield :js %>
  </head>

  <body >
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href= <%= home_path %> >
      <img src= <%= image_path 'flash-sale-logo-navbar.jpg' %> width="130" height="80" alt=""></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" href= <%= home_path %> >Home <span class="sr-only">(current)</span></a>
          <% if current_user.present? %>
            <%= link_to "My Profile", my_profile_users_path, class: "nav-item nav-link" %>
            <%= link_to "My Orders", orders_path, class: "nav-item nav-link" %>
            <%= link_to "SignOut", logout_path, method: :delete, class: "nav-item nav-link" %>
          <% else %>
            <a class="nav-item nav-link" href= <%= new_user_path %>>Sign Up</a>
            <a class="nav-item nav-link" href= <%= login_path %>>Sign In</a>
          <%end%>
        </div>
      </div>
    </nav>
    <br>
    <% flash_bootstrap_class = {
      'alert' => 'alert-warning',
      'notice' => "alert-success",
      'error' => "alert-danger"
    } %>
    <div class = "site-wrapper shadow-lg p-3 mb-5 bg-light rounded">
      <div class = "text-center" id="flash">
        <% flash.each do |type| %>
          <aside class = "alert <%=  flash_bootstrap_class[type[0]] %>" > <%= type[1] %></aside>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>